version: '3.7'

services:
  nextjs_app:
    image: your_nextjs_image:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    ports:
      - "3000:3000"
